=== consenlabs/eos-bp-profile/src/schema.json
{
  "title": "BlockProducer",
  "description": "Information about a block producer on the EOS blockchain",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "desc": {
      "zh": {
        "type": "string",
        "minLength": 1
      },
      "en": {
        "type": "string",
        "minLength": 1
      }
    }
  },
  "type": "object",
  "required": [
    "title",
    "tagline",
    "introduce",
    "account_name",
    "public_key",
    "org",
    "nodes"
  ],
  "additionalProperties": false,
  "properties": {
    "title": {
      "type": "string",
      "minLength": 1
    },
    "tagline": {
      "type": "object",
      "$ref": "#/definitions/desc"
    },
    "introduce": {
      "type": "object",
      "$ref": "#/definitions/desc"
    },
    "account_name": {
      "$id": "/properties/account_name",
      "description": "Producer account name",
      "type": "string",
      "maxLength": 12,
      "minLength": 1
    },
    "public_key": {
      "$id": "/properties/public_key",
      "description": "Public key starting with EOS",
      "type": "string"
    },
    "org": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1
        },
        "website": {
          "$id": "/properties/org/properties/website",
          "description": "Organization website",
          "type": "string"
        },
        "email": {
          "$id": "/properties/org/properties/email",
          "description": "Organization email",
          "type": "string"
        },
        "location": {
          "type": "string",
          "minLength": 1
        },
        "branding": {
          "type": "object",
          "properties": {
            "logo": {
              "type": "string"
            },
            "cover": {
              "type": "string"
            }
          }
        },
        "social_network": {
          "type": "object",
          "properties": {
            "facebook": {
              "description": "group/page address only, not the entire url",
              "type": "string"
            },
            "github": {
              "description": "username only",
              "type": "string"
            },
            "keybase": {
              "description": "username only",
              "type": "string"
            },
            "reddit": {
              "description": "username only",
              "type": "string"
            },
            "steemit": {
              "description": "username only, WITHOUT @",
              "type": "string"
            },
            "telegram": {
              "description": "username only",
              "type": "string"
            },
            "twitter": {
              "description": "username only",
              "type": "string"
            },
            "wechat": {
              "description": "username only",
              "type": "string"
            },
            "youtube": {
              "description": "channel address only",
              "type": "string"
            }
          }
        }
      },
      "required": [
        "name",
        "location",
        "website"
      ]
    },
    "nodes": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "properties": {
          "location": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              }
            }
          },
          "is_producer": {
            "description": "Is this node a producer?",
            "type": "boolean"
          },
          "p2p_endpoint": {
            "description": "EOSIO P2P endpoint (host:port)",
            "type": "string"
          },
          "api_endpoint": {
            "description": "EOSIO HTTP endpoint (http://host:port)",
            "type": "string"
          },
          "ssl_endpoint": {
            "description": "EOSIO HTTPS endpoint (https://host:port)",
            "type": "string"
          }
        }
      }
    }
  }
}

=== consenlabs/eos-bp-profile/bp/eos_asia.json
{
  "title": "EOS Asia",
  "tagline": {
    "en": "Asia's most international and technically experienced BP candidate! We create, inspire, and fund DApps to take EOS to mainstream adoption.",
    "zh": "亚洲最国际化且技术经验丰富的节点候选人！我们创建和孵化 EOS DApp，让EOS成为主流技术。"
  },
  "introduce": {
    "en": "We are the Avengers of the EOS community. EOS Asia has an all-star founding team that brings together wizards of China, Europe, United States and South Korea. Our core technical members are backed by Silicon Valley incubator Y Combinator and recognized by well-known industry veterans. With 15 years of experience in server and cloud technology, we are handling applications for tens of millions of users. Our team: Dafeng is EOS Asia cofounder and CTO of Strikingly, where he graduated from Y Combinator in 2013; Joseph is EOS Asia cofounder and the founder of EOS Link, EOS Go China ambassador, guest writer for NEO City of Zion, and cofounder of webao.co; Jinma is head of operations in China for EOS Asia, he is the founder of Xiaoma Capital (笑马资本) and creator of the brand “Crypto Golden Horse Award” (币圈金马奖) and a crypto KOL.John Yoon is head of operations in Korea for EOS Asia and the head editor of Startup Radar, a startup tech media platform that helps Korean startups go global; Tyler Diaz is Blockchain Developer & Evangelist.",
    "zh": "EOS Asia 拥有全明星团队，正如复仇者联盟一样，阵容强大，汇集美国、欧洲、中国、和韩国的超级大脑。EOS Asia 的核心成员，得到了硅谷孵化器 Y Combinator 的支持，也受到了知名黑客的认可，我们拥有超过 15 年的服务器和云技术经验，处理过千万用户级的应用程序。团队如下：郭达峰，EOS Asia 联合创始人，Strikingly 联合创始人兼CTO，香港中文大学荣誉毕业生；Joseph ，意大利人。EOS Asia 联合创始人，EOS Link 创始人， EOS Go 中国大使，City of Zion 特邀撰稿人，微包网站开发 CEO。李金马，中国运营负责人，「笑马资本」创始人，「币圈金马奖」品牌创建者，「金马带你定投区块链」社群创建者，区块链圈 KOL。John Yoon，韩国区运营负责人，「Startup Radar」的主编。Tyler Diaz 来自美国，区块链开发者和技术布道师，是一位资深开发人员。"
  },
  "account_name": "eosasia11111",
  "public_key": "EOS76gG6ATpqfVf5KrVjh3f4JAa4EKzAwWabTucNQ4Xv2TmVAj9bN",
  "org": {
    "name": "EOS Asia",
    "website": "https://www.eosasia.one/",
    "email": "bp@eosasia.one",
    "branding":{
      "logo": "logo-eos_asia.png",
      "cover": "cover-eos_asia.png"
    },
    "location": "Hong Kong",
    "social_network": {
      "steemit": "https://steemit.com/@eos-asia",
      "twitter": "https://twitter.com/eosasia_one",
      "github": "https://github.com/eosasia",
      "telegram": "https://t.me/EOSAsia"
    }
  },
  "nodes": [
    {
      "location": {
        "name": "Changhua",
        "country": "TW",
        "latitude": 24.0518,
        "longitude": 120.5161
      },
      "is_producer": true,
      "p2p_endpoint": "https://peering1.mainnet.eosasia.one/",
      "api_endpoint": "https://api1.eosasia.one/",
      "ssl_endpoint": "https://api1.eosasia.one/"
    }
  ]
}

=== consenlabs/eos-bp-profile/bp/jeda.json
{
	"title": "JEDA",
	"tagline": {
		"en": "We are committed to promoting EOS in Japan and organize the developer to build the EOS ecosystem.",
		"zh": "我们致力于促进EOS在日本的事业并且组织开发人员构建EOS生态系统。"
	},
	"introduce": {
		"en": "JEDA(Japan EOS Developer Association) which establish in Tokyo Japan. Committed to supporting and building the ecological system of EOS in Japan. Assist DAPP project development and provide other EOS-based services. We will regularly hold online/offline and other format of event, to promoting the acknowledge of EOS .Holding the developing competition and give the reward to the excellent developer.",
		"zh": "一般社团法人EOS开发者协会(Japan EOS Developer Association, 一般社団法人EOS開発者協会，简称JEDA)立足于日本，以支援日本地区EOS生态发展为基本，深度参与项目生态建设。积极组织线上线下活动，召集EOS开发者开发有吸引力的Dapp，并且开发基于EOS的多种服务。"
	},
	"account_name": "jedaaaaaaaaa",
	"public_key": "EOS5XP49jx9eJNQZjqvP7pfKNaAe5JmyAbPZMdsiqD61QQEExqUYe",
	"org": {
		"name": "JEDA",
		"website": "http://www.eosjapan.org",
		"email": "info@www.eosjapan.org",
		"branding": {
			"logo": "logo-jeda.png",
			"cover": "cover-jeda.png"
		},
		"location": "Tokyo, Japan",
		"social_network": {
			"steemit": "https://steemit.com/@eosjapan",
			"twitter": "https://twitter.com/eosjapan_jeda",
			"facebook": "https://www.facebook.com/eosjapan/",
			"github": "http://github.com/eosjapan/",
			"telegram": "https://t.me/eosjapan"
		}
	},
	"nodes": [
    {
      "location": {
        "name": "Tokyo",
        "country": "JP",
        "latitude": 35.679105,
        "longitude": 139.779609
      },
      "is_producer": false,
      "p2p_endpoint": "p.jeda.one:3322",
      "api_endpoint": "",
      "ssl_endpoint": ""
    }
  ]
}

=== consenlabs/eos-bp-profile/bp/eospaceioeos.json
{
  "title": "EOSpace",
  "tagline": {
    "en": "Dedicated to becoming the best witness node.",
    "zh": "致力于成为最好的见证人节点。"
  },
  "introduce": {
    "en": "The EOSpace team core initiating members consist of a number of traditional Internet giants, including the founder of the Nasdaq listed company, the vice president of the A-share listed company, the technical leader of the Unicorn project, and the important code on the github of EOS.IO. Contributors, and distributed throughout the world: China, Singapore, the United States, Europe, etc. Details of specific core team members can be found on the official website: http://www.eospace.io",
    "zh": "EOSpace团队核心发起成员由多位传统互联网的大佬组成，里头包含纳斯达克上市公司创始人，A股上市公司副总裁，独角兽项目技术负责人，EOS.IO的github上的重要代码贡献者，并分布于全球各地：中国，新加坡，美国，欧洲等。具体核心团队成员介绍详见官网：http://www.eospace.io"
  },
  "account_name": "eospaceioeos",
  "public_key": "EOS7dZPHgFJXwHz84JWf5QgybxLpp95cxYE5c4yngsrSqgVFczaPs",
  "org": {
    "name": "EOSpace",
    "website": "https://eospace.io",
    "email": "contact@eospace.io",
    "branding":{
      "logo": "logo-eospaceioeos.png",
      "cover": "cover-eospaceioeos.png"
    },
    "location": "Beijing, China",
    "social_network": {
      "steemit": "https://steemit.com/@noprom",
      "github": "https://github.com/EOSBlock",
      "telegram": "https://t.me/eospace"
    }
  },
  "nodes": [
    {
      "location": {
        "id": "eospace-node-log",
        "name": "Los Angeles"
      },
      "is_producer": false,
      "p2p_endpoint": "p2p.mainnet.eospace.io:88",
      "api_endpoint": "https://api.mainnet.eospace.io",
      "ssl_endpoint": "https://api.mainnet.eospace.io"
    },
    {
      "location": {
        "id": "eospace-node-saf",
        "name": "San Francisco"
      },
      "is_producer": false,
      "p2p_endpoint": "p2p.mainnet.eospace.io:88",
      "api_endpoint": "https://api.mainnet.eospace.io",
      "ssl_endpoint": "https://api.mainnet.eospace.io"
    }
  ]
}

=== consenlabs/eos-bp-profile/bp/eos90s.json
{
  "title": "eos90s",
  "tagline": {
    "en": "The young power",
    "zh": "年轻的力量"
  },
  "introduce": {
    "en": "EOS90s is a Chinese team dedicated to promoting EOS ecology to the general public.",
    "zh": "EOS90s是一个专注于向普通大众宣传EOS生态的中国团队"
  },
  "account_name": "eosninetiess",
  "public_key": "EOS7eMeo7dgG42NQPy4x45X2VhG8T3gjnwuSdsoGeGzz1w3Hwrr7m",
  "org": {
    "name": "eos90后",
    "website": "http://www.eos90s.io",
    "email": "",
    "branding":{
      "logo": "logo-eos90s.png",
      "cover": "cover-eos90s.png"
    },
    "location": "Changsha, China",
    "social_network": {
      "steemit": "https://steemit.com/@eos90s",
      "twitter": "https://twitter.com/Eos90S",
      "facebook": "",
      "github": "",
      "telegram": "https://t.me/EOS90s"
    }
  },
  "nodes": [
    {
      "location": {
        "id": "81",
        "name": "Tokyo, Japan"
      },
      "is_producer": false,
      "p2p_endpoint": "http://mainnet.eos90s.io:6789",
      "api_endpoint": "http://mainnet.eos90s.io",
      "ssl_endpoint": ""
    }
  ]
}

=== consenlabs/eos-bp-profile/bp/geos.json
{
    "title":"GEOS",
    "tagline":{
        "en":"Born unique, greater because of EOS.",
        "cn":"生而不凡，因EOS更伟大"
    },
    "introduce":{
        "en":"GEOS is registered in Singapore and has offices in Beijing and Shanghai. The team of GEOS are from GDEX.io and Magicwallet (www.magicw.net), both of which are well known in BitShares community due to their technology accumulation. GEOS aims to explore the feasibility of combining Bitshares ecosystem with EOS ecosystem, by means of building developers’ community, incubating projects, researching the technology, building API servers and tokenizing the assets.",
        "cn":"公司总部位于新加坡，并在上海和北京设有办事处。由深耕Bitshares生态并为社区做出卓越贡献的GDEX、鼓鼓钱包联合发起，旨在探索Bitshares生态和EOS生态高效、完美结合。GEOS将专注EOS生态建设，建立开发者社区、孵化项目、帮助项目落地、资产流转、扶持API Server等，并协同其他共建者，共同繁荣EOS大生态。"
    },
    "account_name":"geosoneforbp",
    "public_key":"EOS7CjPeMYUj2Ydmw667JJNsQA5mige9YE4FVxMCT81Jst3SRVbX3",
    "org":{
        "name":"GEOS",
        "website":"https://www.geos.one/",
        "email":"geos.one@wichain.net",
        "branding":{
            "logo":"logo-geos.png",
            "cover":"cover-geos.png"
        },
        "location":"Singapore",
        "social_network":{
            "steemit":"https://steemit.com/@geos.one",
            "twitter":"https://twitter.com/geos_team",
            "github":"",
            "telegram":"https://t.me/GDEXer"
        }
    },
    "nodes":[
        {
            "location":{
                "id":"",
                "name":""
            },
            "is_producer":false,
            "p2p_endpoint":"bp.geos.one:80",
            "api_endpoint":"",
            "ssl_endpoint":""
        }
    ]
}

=== consenlabs/eos-bp-profile/bp/germaneostop.json
{
  "title": "GermanEOS",
  "tagline": {
    "en": "EOS Block Producer Candidate made-in-Germany",
    "zh": "来自德国的EOS社区",
	"de": "EOS Block Producer aus Deutschland"
  },
  "introduce": {
   "en": "We are GermanEOS, the Block Producer Candidate from Germany. We are wings of EOS with the goal to strengthen the influence of EOS platform in Germany and to assist the promotion and application of EOS blockchain technology in Germany. GermanEOS aim at being one of the best EOS nodes on the world by adopting class-leading infrastructure, technology, and community building strategy. In addition, GermanEOS will enhance the blockchain technology for universal education, knowledge sharing and incubation projects. GermanEOS is a user-centric community and organized by a group of blockchain enthusiasts. We are truly excited by the technology powering the EOS platform. The GermanEOS community believes that the blockchain technology, EOS in particular, has the potential to be something groundbreaking that will significantly change many of the business areas that are currently working with centralized architectures. GermanEOS will operate as a user-centric community. It aims at being the largest EOS community in Germany. We promote the development of decentralized applications (DAPP) of EOS platform and other blockchain-based technology in the area of energy (SmartEnergy), finance (Coiner.world), logistics, and water. GermanEOS will provide class-leading infrastructures to support the main EOS network. Substantial efforts will be invested in protecting GermanEOS nodes from DDOS attacks.GermanEOS belongs to the whole EOS community and no single person or legal entity should ever control it.",
   "zh": "我们是GermanEOS，来自德国的Block Producer Candidate。我们是EOS的翅膀，目标是加强EOS平台在德国的影响力，并协助EOS区块链技术在德国的推广和应用。 GermanEOS旨在通过采用领先的基础设施，技术和社区建设战略，成为全球最佳EOS节点之一。此外，德国EOS将加强区块链技术，用于普及教育，知识共享和孵化项目。 GermanEOS是一个以用户为中心的社区，由一群区块链爱好者组织。 EOS平台的技术令我们非常兴奋。德国EOS社区认为区块链技术尤其是EOS具有开创性的潜力，这将大大改变目前与集中式架构合作的许多业务领域。 GermanEOS将以用户为中心的社区运作。它的目标是成为德国最大的EOS社区。我们在能源（智能能源），金融（Coiner.world），物流和水领域促进EOS平台和其他基于区块链技术的分散应用（DAPP）的发展。 GermanEOS将提供一流的基础设施来支持主要的EOS网络。将大量的努力用于保护德国EOS节点免受DDOS攻击。GermanEOS属于整个EOS社区，任何单个人或法人都不应该控制它。",
   "de": "Wir sind GermanEOS, der Block Producer Candidate aus Deutschland. Wir sind Flügel von EOS mit dem Ziel, den Einfluss der EOS-Plattform in Deutschland zu stärken und die Förderung und Anwendung der EOS-Blockchain-Technologie in Deutschland zu unterstützen. GermanEOS zielt darauf ab, einer der besten EOS-Knoten auf der Welt zu sein, indem es eine führende Infrastruktur-, Technologie- und Community-Building-Strategie einführt. Darüber hinaus wird GermanEOS die Blockchain-Technologie für universelle Bildung, Wissensaustausch und Inkubationsprojekte erweitern. GermanEOS ist eine benutzerzentrierte Community und wird von einer Gruppe von Blockchain-Enthusiasten organisiert. Wir sind wirklich begeistert von der Technologie, die die EOS-Plattform antreibt. Die GermanEOS-Community glaubt, dass die Blockchain-Technologie, insbesondere EOS, das Potenzial hat, bahnbrechend zu sein, was viele der Geschäftsbereiche, die derzeit mit zentralisierten Architekturen arbeiten, erheblich verändern wird. GermanEOS wird als benutzerzentrierte Community agieren. Ziel ist es, die größte EOS-Community in Deutschland zu sein. Wir fördern die Entwicklung von dezentralen Anwendungen (DAPP) der EOS-Plattform und anderer blockchain-basierter Technologie in den Bereichen Energie (SmartEnergy), Finanzen (Coiner.world), Logistik und Wasser. GermanEOS wird erstklassige Infrastrukturen bereitstellen, um das EOS-Hauptnetzwerk zu unterstützen. Erhebliche Anstrengungen werden unternommen, um GermanEOS-Knoten vor DDOS-Angriffen zu schützen. GermanEOS gehört zur gesamten EOS-Gemeinschaft, und keine einzelne Person oder juristische Person sollte es jemals kontrollieren."
  },
  "account_name": "germaneostop",
  "public_key": "EOS83SYvZgxFZxugkzjy1n5cxNr4xYL27wGxDY4yvszDxXWwx9RnW",
  "org": {
    "name": "GermanEOS",
    "website": "http://www.germaneos.de",
    "email": "info@germaneos.de",
    "branding":{
      "logo": "logo-germaneostop.png",
      "cover": "cover-germaneostop.png"
    },
    "location": "Bonn, Germany",
    "social_network": {
      "steemit": "https://steemit.com/@germaneos",
      "twitter": "https://twitter.com/germaneos",
      "telegram": "https://t.me/germaneos"
    }
  },
  "nodes": [
    {
      "location": {
        "id": "49",
        "name": "Germany"
      },
      "is_producer": false,
      "p2p_endpoint": "",
      "api_endpoint": "",
      "ssl_endpoint": ""
    }
  ]
}

=== consenlabs/eos-bp-profile/bp/eoschainclub.json
{
  "title": "EOS ChainClub",
  "tagline": {
    "en": "Build an EOS Super University",
    "zh": "共建一所EOS超级大学"
  },
  "introduce": {
    "en": "EOS ChainClub was founded by ChainClub, a professional blockchain learning community with more than 10,000 members worldwide. We aim to link everyone in the community with education and incubation. Our goal is to build an EOS Super University and enable everyone to contribute to the EOS ecosystem.",
    "zh": "EOS ChainClub 由专业的区块链学习社群『区块链研习社』组建，我们致力于通过高价值、多维度的社群矩阵，打造EOS普及推广、教育培训、项目孵化闭环，让每一个参与者实现个人成长的同时，为EOS生态持续贡献价值。共建一所分布式学习、链接与协作的“EOS 超级大学”，让全球的EOS支持者与开发者参与到EOS生态建设中来。"
  },
  "account_name": "chainclubeos",
  "public_key": "EOS6bTR5gkBdGQhbM6uFYMYdc2kugU2FUA3XD5soHSCt1pXbGjHjn",
  "org": {
    "name": "EOS ChainClub",
    "website": "https://eosio.university/",
    "email": "admin@eosio.university",
    "branding":{
      "logo": "logo-chainclubeos.png",
      "cover": "cover-eoschainclub.png"
    },
    "location": "Australia",
    "social_network": {
      "steemit": "https://steemit.com/@eoschainclub/",
      "twitter": "https://twitter.com/eoschainclub",
      "github": "https://github.com/BlockChainClub",
      "telegram": "https://t.me/eoscc"
    }
  },
  "nodes": [
    {
      "location": {
        "id": "61",
        "name": "Sydney,Australia"
      },
      "is_producer": true,
      "p2p_endpoint": "bp.eosio.university:9876",
      "api_endpoint": "",
      "ssl_endpoint": ""
    }
  ]
}

=== consenlabs/eos-bp-profile/bp/eosphereiobp.json
{
  "title": "EOSphere",
  "tagline": {
    "en": "Australian based, and serving the entire EOSPhere",
    "zh": "总部设在澳大利亚，但服务于整个EOSphere"
  },
  "introduce": {
    "en": "EOSphere are a passionate group of EOS enthusiasts and data centre professionals campaigning for election as founding block producers for the EOS Mainnet. Based in Australia, EOSphere are focussed on bootstrapping the EOS community and serving the entire EOSphere through provision of infrastructure, governance and community benefit initiatives",
    "zh": "EOSphere是一群充满热情的EOS爱好者和数据中心专业人士，他们竞选EOS Mainnet的创始人。 总部位于澳大利亚，EOSphere致力于引导EOS社区，并通过提供基础设施，治理和社区惠益举措为整个EOSphere服务"
  },
  "account_name": "eosphereiobp",
  "public_key": "EOS5FYRrG3ThNU56d3uZ8d4bo4MsN5Fig9WPY3xYSpH3RqPhpoH3A",
  "org": {
    "name": "EOSphere",
    "website": "https://www.eosphere.io/",
    "email": "info@eosphere.io",
    "branding":{
      "logo": "logo-eosphere.png",
      "cover": "cover-eosphere.png"
    },
    "location": "Perth, Australia",
    "social_network": {
      "steemit": "https://steemit.com/@eosphere",
      "twitter": "https://twitter.com/eosphere_io",
      "facebook": "https://www.facebook.com/eosphereio",
      "github": "https://github.com/eosphere",
      "telegram": "https://t.me/@rossco99"
    }
  },
  "nodes": [
    {
      "location": {
        "id": "61",
        "name": "Australia"
      },
      "is_producer": false,
      "p2p_endpoint": "node1.eosphere.io:9876",
      "api_endpoint": "node1.eosphere.io:8888",
      "ssl_endpoint": "node1.eosphere.io:443"
    }
  ]
}
