=== consenlabs/eos-bp-profile/src/schema.json
{
  "title": "BlockProducer",
  "description": "Information about a block producer on the EOS blockchain",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "desc": {
      "zh": {
        "type": "string",
        "minLength": 1
      },
      "en": {
        "type": "string",
        "minLength": 1
      }
    }
  },
  "type": "object",
  "required": [
    "title",
    "tagline",
    "introduce",
    "account_name",
    "public_key",
    "org",
    "nodes"
  ],
  "additionalProperties": false,
  "properties": {
    "title": {
      "type": "string",
      "minLength": 1
    },
    "tagline": {
      "type": "object",
      "$ref": "#/definitions/desc"
    },
    "introduce": {
      "type": "object",
      "$ref": "#/definitions/desc"
    },
    "account_name": {
      "$id": "/properties/account_name",
      "description": "Producer account name",
      "type": "string",
      "maxLength": 12,
      "minLength": 1
    },
    "public_key": {
      "$id": "/properties/public_key",
      "description": "Public key starting with EOS",
      "type": "string"
    },
    "org": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1
        },
        "website": {
          "$id": "/properties/org/properties/website",
          "description": "Organization website",
          "type": "string"
        },
        "email": {
          "$id": "/properties/org/properties/email",
          "description": "Organization email",
          "type": "string"
        },
        "location": {
          "type": "string",
          "minLength": 1
        },
        "branding": {
          "type": "object",
          "properties": {
            "logo": {
              "type": "string"
            },
            "cover": {
              "type": "string"
            }
          }
        },
        "social_network": {
          "type": "object",
          "properties": {
            "facebook": {
              "description": "group/page address only, not the entire url",
              "type": "string"
            },
            "github": {
              "description": "username only",
              "type": "string"
            },
            "keybase": {
              "description": "username only",
              "type": "string"
            },
            "reddit": {
              "description": "username only",
              "type": "string"
            },
            "steemit": {
              "description": "username only, WITHOUT @",
              "type": "string"
            },
            "telegram": {
              "description": "username only",
              "type": "string"
            },
            "twitter": {
              "description": "username only",
              "type": "string"
            },
            "wechat": {
              "description": "username only",
              "type": "string"
            },
            "youtube": {
              "description": "channel address only",
              "type": "string"
            }
          }
        }
      },
      "required": [
        "name",
        "location",
        "website"
      ]
    },
    "nodes": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "properties": {
          "location": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              }
            }
          },
          "is_producer": {
            "description": "Is this node a producer?",
            "type": "boolean"
          },
          "p2p_endpoint": {
            "description": "EOSIO P2P endpoint (host:port)",
            "type": "string"
          },
          "api_endpoint": {
            "description": "EOSIO HTTP endpoint (http://host:port)",
            "type": "string"
          },
          "ssl_endpoint": {
            "description": "EOSIO HTTPS endpoint (https://host:port)",
            "type": "string"
          }
        }
      }
    }
  }
}

=== consenlabs/eos-bp-profile/bp/acroeos.json
{
  "title": "AcroEOS",
  "tagline": {
    "en": "AcroEOS connects EOS to real world",
    "zh": "AcroEOS，连接EOS与现实世界"
  },
  "introduce": {
    "en": "AcroEOS is based on the capability of financial technology experience. We can support EOS projects establish in proper regulatory manner, utilizing our licenses of financial technology industry and over 5,000 merchant network. By leveraging all of this, we plan to promote and drive widespread usage of EOS among consumers and businesses.",
    "zh": "AcroEOS由专业的金融科技经验所支撑。我们已具备移动支付、跨境汇款等运营金融科技业务所需牌照和5000多家支付加盟商网络，并可以在监管框架内合法落地EOS项目。利用这些优势，我们将把EOS技术广泛地普及到消费者和商业场景中。"
  },
  "account_name": "acroeos12345",
  "public_key": "EOS56PyKoHXwyRkwDzr2uNhgDRioPoq5TwdN8Pm2hQGko7jrup2W5",
  "org": {
    "name": "AcroEOS",
    "website": "https://www.acroeos.io/",
    "email": "community@acroeos.io",
    "branding":{
      "logo": "logo-acroeos.png",
      "cover": "cover-acroeos.png"
    },
    "location": "Seoul, Korea",
    "social_network": {
      "steemit": "https://steemit.com/@acroeos",
      "twitter": "https://twitter.com/acroeos",
      "facebook": "https://www.facebook.com/acroeos",
      "github": "https://github.com/acroeos",
      "telegram": "https://t.me/AcroEOS"
    }
  },
  "nodes": [
    {
      "location": {
        "id": "82",
        "name": "South Korea"
      },
      "is_producer": false,
      "p2p_endpoint": "",
      "api_endpoint": "",
      "ssl_endpoint": ""
    }
  ]
}

=== consenlabs/eos-bp-profile/bp/franceos.json
{
  "title": "franceos",
  "tagline": {
    "en": "CREATING SHARED VALUE FOR THE EOS COMMUNITY",
    "zh": ""
  },
  "introduce": {
    "en": "franceos is a gathering of French-speaking and involved crypto-enthusiasts, candidating for a block production position on the EOS decentralized network.",
    "zh": ""
  },
  "account_name": "franceosysbp",
  "public_key": "EOS7FurktbYTCLzwVpjckHxC2Wx1zuWysUzyjWXhG9fm9E2geV6ZA",
  "org": {
    "name": "franceos",
    "website": "https://www.franceos.fr",
    "email": "hello@franceos.fr",
    "branding":{
      "logo": "logo-franceos.png",
      "cover": "cover-franceos.png"
    },
    "location": "Toulouse & Lille, France",
    "social_network": {
      "steemit": "https://steemit.com/@franceos",
      "twitter": "https://twitter.com/franceos__",
      "github": "https://github.com/franceos",
      "telegram": "https://t.me/franceos"
    }
  },
  "nodes": [
    {
      "location": {
        "id": "33",
        "name": "france"
      },
      "is_producer": false,
      "p2p_endpoint": "p2p.franceos.fr:1987",
      "api_endpoint": "",
      "ssl_endpoint": ""
    }
  ]
}

=== consenlabs/eos-bp-profile/bp/genereos.json
{
  "title": "GenerEOS",
  "tagline": {
    "en": "A vote for GenerEOS is a vote for Charity!",
    "zh": "投票GenerEOS，就是你对慈善事业的投票！"
  },
  "introduce": {
    "en": "GenerEOS is a social enterprise block producing candidate with a mission of promoting and supporting scalable and highly reliable block production whilst giving back block rewards to charities. Based out of Sydney, Australia, GenerEOS is founded by a team of like minded blockchain enthusiasts with diverse backgrounds and a passion to make a difference in the world and fostering the spirit of generosity by giving back.",
    "zh": "GenerEOS是专业超级节点候选人，它的使命是建立一个促进，可持续发展和高度可靠的区块链生产，同时对慈善事业带来益处。GenerEOS总部设在澳大利亚的悉尼，由一群志同道合的区块链专业人士组成。他们虽拥有不同背景，却共有让世界不再一样的热诚，并努力把GenerEOS塑造成慷慨回馈社会的典范。"
  },
  "account_name": "aus1genereos",
  "public_key": "EOS57ZyzVjoEG2bvzmYmmeiH8YnYtRudxNKxppx17q7Hg29F8tW4t",
  "org": {
    "name": "GenerEOS",
    "website": "https://www.genereos.io",
    "email": "contact@genereos.io",
    "branding":{
      "logo": "logo-genereos.png",
      "cover": "cover-genereos.png"
    },
    "location": "Sydney, Australia",
    "social_network": {
      "steemit": "https://steemit.com/@genereos",
      "twitter": "https://twitter.com/genereossydney",
      "facebook": "https://www.facebook.com/generEOS",
      "github": "https://github.com/generEOS",
      "telegram": "https://t.me/generEOS"
    }
  },
  "nodes": [
    {
      "location": {
        "id": "61",
        "name": "Australia"
      },
      "is_producer": false,
      "p2p_endpoint": "p2p.genereos.io:9876",
      "api_endpoint": "http://mainnet.genereos.io",
      "ssl_endpoint": "https://mainnet.genereos.io"
    },
    {
      "location": {
        "id": "61",
        "name": "Australia"
      },
      "is_producer": true,
      "p2p_endpoint": "",
      "api_endpoint": "",
      "ssl_endpoint": ""
    }
  ]
}

=== consenlabs/eos-bp-profile/bp/EOSIO.SG.json
{
  "title": "EOSIO.SG",
  "tagline": {
    "en": "Build a better world with EOS",
    "zh": "与EOS共建美好世界"
  },
  "introduce": {
    "en": "EOSIO.SG, based in Singapore, concentrates on low-level blockchain technology. ",
    "zh": "EOSIO.SG，来自新加坡的EOS节点候选团队，专注区块链底层技术研究。"
  },
  "account_name": "eosiosg11111",
  "public_key": "EOS7zVBQMhV7dZ5zRQwBgDmmbFCHA6YcmwW6Dq5CePGpqLR1ZsVAc",
  "org": {
    "name": "EOSIO.SG",
    "website": "https://eosio.sg",
    "email": "deadlock@eosio.sg",
    "branding":{
      "logo": "logo-eosiosg.png",
      "cover": "cover-eosiosg.png"
    },
    "location": "Singapore, Singapore",
    "social_network": {
      "steemit": "https://steemit.com/@eosiosg",
      "twitter": "https://twitter.com/eosiosg",
      "facebook": "https://www.facebook.com/eosiosg-168790343770758/",
      "github": "https://github.com/eosiosg",
      "telegram": "https://t.me/eosiosg"
    }
  },
  "nodes": [
    {
      "location": {
        "id": "65",
        "name": "Singapore"
      },
      "is_producer": false,
      "p2p_endpoint": "",
      "api_endpoint": "",
      "ssl_endpoint": ""
    },
    {
      "location": {
        "id": "1",
        "name": "U.S."
      },
      "is_producer": true,
      "p2p_endpoint": "",
      "api_endpoint": "",
      "ssl_endpoint": ""
    }
  ]
}

=== consenlabs/eos-bp-profile/bp/eosono.json
{
  "title": "eosONO",
  "tagline": {
    "en": "For EOS ecosystem, for the human! ", 
    "zh": "为生态繁荣，为全人类！"
  },
  "introduce": {
    "en": "ONO is the largest free, decentralized social network. We are committed to creating an ecosystem of attention and value that is free and equal, co-governed and diverse, and now has millions of loyal users worldwide. Recently, competition is increasing in the race to become one of the 21 global Block Producers for EOS and now it appears that the entire blockchain space is scrambling to get involved. eosONO is a strong contender for being chosen as one of the top EOS Block Producers. It has been reported that ONO officially launched in mid-April, and is the first social media dApp to be launched on the EOS platform.", 
    "zh": "ONO，全球最大的自由、去中心化社交网络。致力于打造自由平等、社会共治与多样性的注意力价值生态，现在全球范围内拥有百万忠实用户。ONO，全球最大的自由、去中心化社交网络。致力于打造自由平等、社会共治与多样性的注意力价值生态，现在全球范围内拥有百万忠实用户。2018年3月，eosONO宣布竞选EOS全球21个超级节点，是目前EOS全球超级节点竞选中最强劲候选者之一。2018年5月初，eosONO与硬币资本共同发起并上线了EOS.host测试网络，并邀请了全球EOS超级节点优秀候选者加入测试。eosONO将为EOS生态繁荣提供最大的支持，包括：海量的社交网络用户支持；为全球网络用户提供计算和带宽支持；为基于EOS DAPP生态发展提供建议、帮助和支持。eosONO也已经做好了肩负服务全人类的使命，将与全球其他20个超级节点共建秩序生态网络。"
  },
  "account_name": "eosonoeosono",
  "public_key": "EOS5AHfFwaJxjMPkrufw4aCTFvJJUVgpwqwvghhYrFahik7oxaXah",
  "org": {
    "name": "eosONO",
    "website": "https://ono.chat",
    "email": "service@ono.chat",
    "branding":{
      "logo": "logo-eosono.png",
      "cover": "cover-eosono.png"
    },
    "location": "Beijing, China",
    "social_network": {
      "steemit": "https://steemit.com/@onosocial",
      "twitter": "https://twitter.com/onosocial",
      "facebook": "https://m.facebook.com/onosocial",
      "telegram": "https://t.me/ONOCN"
    }
  },
  "nodes": [
    {
      "location": {
        "id": "81",
        "name": "Tokyo, Japan"
      },
      "is_producer": false,
      "p2p_endpoint": "",
      "api_endpoint": "http://api-eos.ono.chat",
      "ssl_endpoint": "https://api-eos.ono.chat"
    }
  ]
}

=== consenlabs/eos-bp-profile/bp/eoscybexiobp.json
{
  "title": "EOS.CYBEX",
  "tagline": {
    "en": "Of the community, by the community, for the communtiy",
    "zh": "社区共有，社区共治，社区共享"
  },
  "introduce": {
    "en":
      "EOS.CYBEX is a unique ecosystem dedicated to EOS founded by James Gong, an early blockchain practitioner in China. It integrates a decentralized exchange CYBEX, global incubation as well as serious news agency namely LongHash, another established news platform called ChainB, and a dev team which will  soon launch world’s first multi-signature hardware wallet for EOS. The founder of EOS.CYBEX, James Gong starts ICOAGE (formerly the largest ICO platform in China) and ChainB (the largest Chinese blockchain media). James has been a leading blockchain and cryptocurrency evangelist and key opinion leader in China since 2012. He has helped to translate innumerable blockchain related articles and whitepapers into Chinese, as well as having authored many books on blockchain, including “The Blockchain Society”, “Blockchain – the New Economy’s Blueprint”, and “Cryptocurrency”.",
    "zh":
      "EOS.CYBEX是一由暴走恭亲王龚鸣发起，为EOS而建立的新社群，整个生态有去中心化交易所CYBEX，全球孵化器及严肃媒体LongHash, 国内知名媒体区块链铅笔，及将来会推出EOS上第一个多签硬件钱包的团队。团队发起人龚鸣创立ICOAGE （曾为中国最大ICO平台）及区块链铅笔（最大中文区块链媒体）。2012年开始致力于推动数字货币和区块链行业的发展，翻译并撰写过大量相关资料和区块链项目白皮书，参与著有《区块链社会》、《区块链——新经济蓝图》、《数字货币》等多部著作。"
  },
  "account_name": "eoscybexiobp",
  "public_key": "EOS517qs2b355FjuM4WgbyVWGkDqm2HJXtc3cVdSDzMAxc7dVm6PL",
  "org": {
    "name": "EOS.CYBEX",
    "website": "https://eos.cybex.io/index_en.html",
    "email": "service@eos.cybex.io",
    "branding": {
      "logo": "logo-EOS_CYBEX.png",
      "cover": "cover-EOS_CYBEX.png"
    },
    "location": "Shanghai, China",
    "social_network": {
      "steemit": "https://steemit.com/@eos.cybex",
      "twitter": "https://twitter.com/EOSCYBEX",
      "facebook": "",
      "github": "",
      "telegram": "https://t.me/eoscybexen"
    }
  },
  "nodes": [
    {
      "location": {
        "id": "852",
        "name": "Hong Kong"
      },
      "is_producer": false,
      "p2p_endpoint": "",
      "api_endpoint": "",
      "ssl_endpoint": ""
    }
  ]
}

=== consenlabs/eos-bp-profile/bp/whateos.json
{
 "title": "Whateos",
 "tagline": {
 "en": "The most powerful community representative in Oceania",
 "zh": "最强大的大洋洲节点"
 },
 "introduce": {
 "en": "Whateos aims to become the democratic node with the highest security and stability and the most powerful EOS super node in Oceania",
 "zh": "Whateos的目标是成为具有最高安全性和稳定性的民主节点，以及大洋洲最强大的EOS超级节点"
 },
 "account_name": "whateosbp111",
 "public_key": "EOS5M4pNafgde3WiQc4LTHgDKcFgB4MvaUsNjugTG5KY65aVoL68w",
 "org": {
 "name": "WhatEOS",
 "website": "http://whateos.com",
 "email": "steven.xu@horman.vc",
 "branding":{
 "logo": "logo-whateosbp111.png",
 "cover": "cover-whateosbp111.png"
 },
 "location": "Melbourne, Australia",
 "social_network": {
 "steemit": " http://twitter.com/Whateos_bp",
 "twitter": " http://twitter.com/Whateos_bp",
 "facebook": "",
 "github": "",
 "telegram": "t.me/whateos"
 }
 },
 "nodes": [
 {
 "location": {
 "id": "",
 "name": ""
 },
 "is_producer": false,
 "p2p_endpoint": "",
 "api_endpoint": "",
 "ssl_endpoint": ""
 }
 ]
 }

=== consenlabs/eos-bp-profile/bp/cryptolions1.json
{
  "title": "CryptoLions",
  "tagline": {
    "en": "Our Values: Sophrosyne, Respect, Competence, Integrity",
    "zh": ""
  },
  "introduce": {
    "en": "EOS Block Producer Candidates based in Ukraine",
    "zh": ""
  },
  "account_name": "cryptolions1",
  "public_key": "EOS5yHaUBwhpwFftNjADdVwBpCVybLPg5P3z7HpTbDGjUfpqwWSSf",
  "org": {
    "name": "CryptoLions",
    "website": "http://cryptolions.io",
    "email": "roar@cryptolions.io",
    "branding":{
      "logo": "logo-cryptolions1.png",
      "cover": "cover-cryptolions1.png"
    },
    "location": "Lviv, Ukraine",
    "social_network": {
      "steemit": "https://steemit.com/@cryptolions",
      "twitter": "https://twitter.com/EOS_CryptoLions",
      "facebook": "",
      "github": "https://github.com/CryptoLions",
      "telegram": "https://t.me/CryptoLions_io"
    }
  },
  "nodes": [
    {
      "location": {
        "id": "49",
        "name": "Germany"
      },
      "is_producer": false,
      "is_producer": false,
      "p2p_endpoint": "bp.cryptolions.io:9876",
      "api_endpoint": "http://bp.cryptolions.io:8888",
      "bnet_endpoint": "bp.cryptolions.io:9875",
      "ssl_endpoint": ""
    },
	{
      "location": {
        "id": "358",
        "name": "Finland"
      },
      "is_producer": false,
      "is_producer": false,
      "p2p_endpoint": "bp.cryptolions.io:9876",
      "api_endpoint": "http://bp.cryptolions.io:8888",
      "bnet_endpoint": "bp.cryptolions.io:9875",
      "ssl_endpoint": ""
    }
  ]
}
