=== consenlabs/eos-bp-profile/src/schema.json
{
  "title": "BlockProducer",
  "description": "Information about a block producer on the EOS blockchain",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "desc": {
      "zh": {
        "type": "string",
        "minLength": 1
      },
      "en": {
        "type": "string",
        "minLength": 1
      }
    }
  },
  "type": "object",
  "required": [
    "title",
    "tagline",
    "introduce",
    "account_name",
    "public_key",
    "org",
    "nodes"
  ],
  "additionalProperties": false,
  "properties": {
    "title": {
      "type": "string",
      "minLength": 1
    },
    "tagline": {
      "type": "object",
      "$ref": "#/definitions/desc"
    },
    "introduce": {
      "type": "object",
      "$ref": "#/definitions/desc"
    },
    "account_name": {
      "$id": "/properties/account_name",
      "description": "Producer account name",
      "type": "string",
      "maxLength": 12,
      "minLength": 1
    },
    "public_key": {
      "$id": "/properties/public_key",
      "description": "Public key starting with EOS",
      "type": "string"
    },
    "org": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1
        },
        "website": {
          "$id": "/properties/org/properties/website",
          "description": "Organization website",
          "type": "string"
        },
        "email": {
          "$id": "/properties/org/properties/email",
          "description": "Organization email",
          "type": "string"
        },
        "location": {
          "type": "string",
          "minLength": 1
        },
        "branding": {
          "type": "object",
          "properties": {
            "logo": {
              "type": "string"
            },
            "cover": {
              "type": "string"
            }
          }
        },
        "social_network": {
          "type": "object",
          "properties": {
            "facebook": {
              "description": "group/page address only, not the entire url",
              "type": "string"
            },
            "github": {
              "description": "username only",
              "type": "string"
            },
            "keybase": {
              "description": "username only",
              "type": "string"
            },
            "reddit": {
              "description": "username only",
              "type": "string"
            },
            "steemit": {
              "description": "username only, WITHOUT @",
              "type": "string"
            },
            "telegram": {
              "description": "username only",
              "type": "string"
            },
            "twitter": {
              "description": "username only",
              "type": "string"
            },
            "wechat": {
              "description": "username only",
              "type": "string"
            },
            "youtube": {
              "description": "channel address only",
              "type": "string"
            }
          }
        }
      },
      "required": [
        "name",
        "location",
        "website"
      ]
    },
    "nodes": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "properties": {
          "location": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              }
            }
          },
          "is_producer": {
            "description": "Is this node a producer?",
            "type": "boolean"
          },
          "p2p_endpoint": {
            "description": "EOSIO P2P endpoint (host:port)",
            "type": "string"
          },
          "api_endpoint": {
            "description": "EOSIO HTTP endpoint (http://host:port)",
            "type": "string"
          },
          "ssl_endpoint": {
            "description": "EOSIO HTTPS endpoint (https://host:port)",
            "type": "string"
          }
        }
      }
    }
  }
}

=== consenlabs/eos-bp-profile/bp/eoshcc.json
{
  "title": "EOSHCC",
  "tagline": {
    "en": "Integrate EOS information of the whole network to establish healthy communities and applications based on eos.hcc",
    "zh": "整合全网EOS资讯,建立基于eos.hcc的健康社区和应用"
  },
  "introduce": {
    "en": "HCC applies the decentralized distributed structure to the medical and health industry to reduce the pain points of huge resource consumption and complicated data circulation, and finally achieve the purpose of reducing the cost of the intermediary; through the security trust mechanism, it can solve the current great health information technology. The certification defect, with the flexible programmability of the blockchain, helps healthcare organizations build outreach applications. CC Personal Health Management Platform APP is a DAPP application under the umbrella of Hcchain; it provides the most comprehensive personal medical records and health management for community members worldwide.",
    "zh": "HCC是将去中心化的分布式结构应用于医疗健康行业，以减少资源耗费巨大、数据流转复杂等行业疼点， 最终达到减少中介成本的目的；通过安 全的信任机制，解决现今大健康信息技术的认证 缺陷，用区块链灵活的可编程特性，帮助医疗健 康机构建立拓展应用。CC个人医疗健康管理平台APP是Hcchain旗下的一个DAPP应用；为全球社区人员提供最全面的个人病历和健康管理。"
  },
  "account_name": "eoshcchealth",
  "public_key": "EOS7qQrBczoy9B892tRY9eir21eBh6S1nUMjZGyJaVY1EDLe7TdvL",
  "org": {
    "name": "EOSHCC",
    "website": "http://eos.hcc.top/index_en.html",
    "email": "help@pu-li.tech",
    "branding":{
      "logo": "logo-eoshcc.png",
      "cover": "cover-eoshcc.png"
    },
    "location": "Crescent, Singapore",
    "social_network": {
      "steemit": "https://steemit.com/@eos.hcc",
      "github": "https://github.com/healthcarechain",
      "telegram": "https://t.me/eos_hcc_node"
    }
  },
  "nodes": [
    {
      "location": {
        "id": "65",
        "name": "Singapore"
      },
      "is_producer": false,
      "p2p_endpoint": "",
      "api_endpoint": "",
      "ssl_endpoint": ""
    }
  ]
}

=== consenlabs/eos-bp-profile/bp/eosgravity.json
{
  "title": "EOS Gravity",
  "tagline": {
    "en": "The Largest EOS Community in the World",
    "zh": "引力区——全球最大的EOS社区"
  },
  "introduce": {
   "en": "As an international team featuring professionalism, EOS Gravity is joined by a group of experienced talents who specialize in community operation and technical development. Liao Yang Yang, the founder of EOS Gravity, obtained his master degree in computer science at Fudan University and is known as the senior evangelist of blockchain technology, the founder of West Miner, the founder of QChain Exchange, Litecoin expert, a famous Litecoin technical analyst and industry tycoon, the author of the analytical article ‘Litecoin Will Not Die’ and the managing director and founder of EOS Gravity. Li Wan Cai (Peter Li) is the co-founder of EOS Gravity. Over 10 years into technical development in scientific research institutions, Li Wan Cai, Ph.D. in computer science from Fudan University, specializes in incubation, investment and technical development of blockchain projects. He is an expert in the field of data encryption, data security and IoT and has published many thesis and patents. Apart from that, he is known as the core member of one of the earliest chip miners groups. With 4 years of study and experience in the cryptocurrency industry, Li Wan Cai is currently the co-founder and director of WaterDrip Capital, the co-founder of Formula Capital and EOS Gravity.",
   "zh": "引力区是一个专业的国际化团队，凝聚了一批经验丰富的社区运营、技术开发的人才队伍。廖洋阳【创始人】：毕业于复旦大学计算机系，复旦大学计算机硕士，区块链资深布道者、西部矿机创始人、秋千交易所创始人、莱特币资深人士，著名莱特币技术分析及行业领袖，2014年’莱特币不会死’的发起者，EOS引力区的主编和创始人。李万才【联合创始人】：博士，毕业于复旦大学计算机系，拥有10年以上科研院所的技术开发经验及数十篇论文专利，数据加密，网络安全及物联网领域专家。早期某知名芯片矿机核心成员，4年数字货币从业经验。水滴资本联合创始人，理事。原力资本（Force.Fund）联合创始人，EOS引力区联合创始人。主要致力于区块链项目孵化，投资和技术开发。"
  },
  "account_name": "eosisgravity",
  "public_key": "EOS55HTTjoxVX1zVpW8pabxygBb1J3SEnG5D8D3y3KgrnSbLpELfE",
  "org": {
    "name": "EOS Gravity",
    "website": "http://eosgravity.com",
    "email": "bp@eosfans.one",
    "branding":{
      "logo": "logo-eosgravity.png",
      "cover": "cover-eosgravity.png"
    },
    "location": "Shanghai, China",
    "social_network": {
      "steemit": "https://steemit.com/@eosgravity",
      "twitter": "https://twitter.com/EOSGravity",
      "weibo": "https://weibo.com/1001ico",
      "telegram": "https://t.me/eosgravity"
    }
  },
  "nodes": [
    {
      "location": {
        "id": "1",
        "name": "Canada"
      },
      "is_producer": false,
      "p2p_endpoint": "",
      "api_endpoint": "",
      "ssl_endpoint": ""
    },
    {
      "location": {
        "id": "81",
        "name": "Japan"
      },
      "is_producer": false,
      "p2p_endpoint": "",
      "api_endpoint": "",
      "ssl_endpoint": ""
    },
    {
      "location": {
        "id": "65",
        "name": "Singapore"
      },
      "is_producer": false,
      "p2p_endpoint": "",
      "api_endpoint": "",
      "ssl_endpoint": ""
    }
  ]
}

=== consenlabs/eos-bp-profile/bp/eosnation.json
{
  "title": "EOS Nation",
  "tagline": {
    "en": "Building our Future one Block at a Time",
    "cn": "同一个区块，同一个时间，同一个未来。"
  },
  "introduce": {
    "en": "EOS Nation is dedicated to fostering the EOS platform through reliable and efficient block production and community engagement. We believe in a future where life, liberty, and property is protected through decentralization. Our mission is to bring together all members of the EOS community under one project. Accessible to the community in jurisdictions around the world. We strive to share our vision for the future of EOS through education and through education, engagement and support. EOS Nation is focused on trying to ignite leadership in ourselves and others... Expecting greatness, we will discover it! A global community is possible, and we aim to make it a reality.",
    "cn": "EOS Nation致力于通过可靠而高效的区块生产和社区经营来促进EOS平台的发展。我们相信通过去中心化能够创造一个生命，自由和财产都受到保护的的未来，我们的使命是将所有的EOS社区成员团结在一个项目中，在全球各地的社区中都能发挥作用。我们努力通过教育，科普，参与和支持来分享我们对EOS未来的展望。EOS Nation一直努力地想激发我们自己和大家所有人的领导力。我们期待成就伟大，我们一定能做到！一个全球化的社区不是痴人说梦，我们的目标就是是使其成为现实。"
  },
  "account_name": "eosnationftw",
  "public_key": "EOS8PkNNBYU1xnbcjBUNm1mT6N68QiGvCDgPT97rqurLBEjDanSXK",
  "org": {
    "name": "EOS Nation",
    "website": "https://eosnation.io",
    "email": "info@eosnation.io",
    "branding":{
      "logo": "logo-eosnation.png",
      "cover": "cover-eosnation.png"
    },
    "location": "Toronto, Canada",
    "social_network": {
      "steemit": "https://steemit.com/@eosnation",
      "twitter": "https://twitter.com/EOS_Nation",
      "facebook": "https://www.facebook.com/groups/EOSNation/",
      "github": "https://github.com/EOS-Nation",
      "telegram": "https://t.me/EOSNation"
    }
  },
  "nodes": [
    {
      "location": {
        "id": "1",
        "name": "Canada",
        "latitude": 43.655045,
        "longitude": -79.381306
      },
      "is_producer": false,
      "p2p_endpoint": "",
      "api_endpoint": "",
      "ssl_endpoint": ""
    }
  ]
}

=== consenlabs/eos-bp-profile/bp/EOSTHU.json
{
  "title": "EOSTHU",
  "tagline": {
    "en": "The first university BP candidate-shuimu tsinghua",
    "zh": "第一个高校节点-水木清华."
  },
  "introduce": {
    "en": "EOSTHU is the first EOS block producer candidate globally which is built in university and focus on EOS technical training for the undergraduates. It is supported by Tsinghua University X-elevator and builds strong relationship with R&D centers in universities and research institutions. We have experienced EOS developing engineers who can offer professional coach to university students. We will provide regular training in universities step by step start from Tsinghua. EOS supporters and community builders will gather together in EOSTHU. Programming competition will be held to find talents on EOS. Besides that, we have built professional blockchain committee for Intellectual Property Protection Alliance. Opportunities will be provided to communicate and work with each other. EOSTHU builds close relationship with investors who will help the EOS developers build their own EOS community. Zhao Wei, Founder of EOSTHU, graduated from School of Economics and Management of Tsinghua University with EMBA degree. He is the secretary-general of the entrepreneurship association of the school of economics and management, Tsinghua university. He is also an angel investor and the innovation and entrepreneurship tutor of \"president cup entrepreneurship competition\" of Tsinghua. He established in 2015 the first intellectual property equity fund guided by national capital - intellectual property equity funds, which is known as the national team or intellectual property funds. He invested on bitcoin miner in 2013 and is in the earliest batch who sensed the value of blockchain. Now he discovers the superiority of EOS and decides to provide the best EOS training course for the undergraduates.",
    "zh": "EOSTHU是全球第一个EOS高校竞选节点。创始人赵伟先生任清华互联网产业研究院知识产权转化实验室主任、清华经管互联网协会首届副会长及理事，同时是清华经管创业协会秘书长、清华大学“校长杯创业大赛”创新创业导师，任清创纪元(清华经管创业者加速器运营公司)副董事长。赵伟先生是一名资深的天使投资人，具有丰富的创投经验；同时是一名资深的区块链应用专家，对区块链在供应链领域、溯源领域及知识产权领域的应用具有独到见解。EOSTHU与高校及科研单位建立了广泛的联系。我们致力于向高校在校生培训区块链尤其是EOS的开发技术，从清华开始逐步扩散至北京及全国各高校。通过举办EOS大赛，我们将发掘优秀的EOS开发者并向投资人做推介。EOSTHU团队拥有丰富的社区产品开发和培训、投资运营经验，在产品研发、业务逻辑设计、流量运营、交互体验优化、课程设计、项目投资等方面有着丰富的经验和技术沉淀。EOSTHU团队自创立之初就坚持探索有用户价值的EOS生态产品，对用户体验的追求几近偏执，EOSTHU将为高频使用场景提供最优雅的产品体验。EOSTHU将成为EOS爱好者的社区，在此聚集了众多EOS的发烧友。DAPP开发者可以从中寻找到用户，对接投资人；技术大咖可以从中找到心仪的项目并加入作为其中的一员；投资人将从中挖掘到优质项目，为整个生态提供支撑。EOSTHU将为EOS开辟一块试验田，搭建EOS生态入口，建设EOS技术人才社区，我们唯一的、根本的目的，是为了让EOS生态更好的服务现实世界。"
  },
  "account_name": "eosthushuimu",
  "public_key": "EOS7mawmWYTjzjt2riNSHKQhA8E86r3L8eXhcotuskGPJU6RNzUZs",
  "org": {
    "name": "EOSTHU",
    "website": "http://www.eosthu.com/",
    "email": "service@flian.com",
    "branding": {
      "logo": "logo-EOSTHU.png",
      "cover": "cover-EOSTHU.png"
    },
    "location": "Beijing, China",
    "social_network": {
      "steemit": "https://steemit.com/@eosthu",
      "twitter": "http://twitter.com/eosthu",
      "github": "https://github.com/eosthu",
      "telegram": "http://t.me/eosthu"
    }
  },
  "nodes": [
    {
      "location": {
        "id": "86",
        "name": "Beijing"
      },
      "is_producer": false,
      "p2p_endpoint": "",
      "api_endpoint": "",
      "ssl_endpoint": ""
    },
    {
      "location": {
        "id": "81",
        "name": "Japan"
      },
      "is_producer": false,
      "p2p_endpoint": "",
      "api_endpoint": "",
      "ssl_endpoint": ""
    },
    {
      "location": {
        "id": "65",
        "name": "Singapore"
      },
      "is_producer": false,
      "p2p_endpoint": "",
      "api_endpoint": "",
      "ssl_endpoint": ""
    }
  ]
}

=== consenlabs/eos-bp-profile/bp/eosswedenorg.json
{
	"title": "eos sw/eden",
	"tagline": {
		"en": "Building Eden Through Blockchain Technology",
		"zh": "通过区块链技术构建伊甸园"
	},
	"introduce": {
		"en": "Our team launched the first successful test network on the EOS Blockchain. We have been an important source of information for BP candidates in the blockchain ecosystem, helping community members understand how to build their own server systems and operate in the EOS chain. One of the driving forces of EOS SW/EDEN is to help people learn how to use their talents and abilities to contribute to the community. This driving force is based on our core values - transparency, integrity, generosity and education.",
		"zh": "我们的团队在EOS Blockchain上推出了第一个成功的测试网。我们一直是区块链生态系统中BP候选人的重要信息来源，帮助社区成员了解如何建立自己的服务器系统并在EOS链中运营。EOS SW/EDEN 的驱动力之一是帮助人们学习如何使用自己的天赋和能力为社区做贡献。这种驱动力建立在我们核心价值观的基础上 - 透明度，诚信，慷慨和教育。"
	},
	"account_name": "eosswedenorg",
	"public_key": "EOS7SGSBsWhSob6TEric6u3TGodcc1uXFcqSrquJ3Etuqcbb3VnNY",
	"org": {
		"name": "eos sw/eden",
		"website": "https://eossweden.se/",
		"email": "community@eossweden.se",
		"branding": {
			"logo": "logo-eosswedenorg.png",
			"cover": "cover-eosswedenorg.png"
		},
		"location": "Sweden",
		"social_network": {
			"steemit": "https://steemit.com/@eos.sw-eden",
			"twitter": "https://twitter.com/eossweden",
			"facebook": "https://www.facebook.com/EOS-sweden-554084258304426/",
			"github": "https://github.com/xebb82",
			"telegram": "https://t.me/eossweden"
		}
	},
	"nodes": [{
		"location": {
			"id": "46",
			"name": "Sweden"
		},
		"is_producer": false,
		"p2p_endpoint": "p2p.eossweden.se:9876",
		"api_endpoint": "http://fn.eossweden.se:80",
		"ssl_endpoint": "https://fn.eossweden.se:443"
	}]
}

=== consenlabs/eos-bp-profile/bp/eospalliums.json
{
  "title": "EOS Palliums",
  "tagline": {
    "en": "Build underlying infrastructure for value Internet, provide neutral multi-dimensional service, and build the cornerstone of social credit in the future.", 
    "zh": "搭建价值互链网底层基础设施，提供中立多维度的服务，做未来信用社会的基石。"
  },
  "introduce": {
    "en": "Palliums is the most influential network infrastructure service provider globally, a valued-added telecom platform, and the largest neutral Internet infrastructure provider for telecom in China. Over the past 20 years, the new era of information infrastructure (data center, decentralized distributed network, CDN, broadband) have been created with high performance, mobility, security and ubiquity through disruptive technology innovation, business model innovation and ecological innovation. Palliums want to continue to exert our full strength in the future value Internet, and are actively engaged in the infrastructure construction of EOS super nodes.", 
    "zh": "Palliums 是全球具有重要影响力的网络空间基础设施创新服务提供商，增值电信服务平台，也是中国最大的电信中立互联网基础设施服务提供商。在过去的20年中，我们通过颠覆性技术创新、商业模式创新和生态创新，构建了高速、移动、安全、泛在的新一代信息基础设施（数据中心、去中心化的分布式网络、CDN、宽带）。Palliums 希望在未来的信任互联网中继续发挥我们所长，积极投入于 EOS 超级节点的基础设施建设。"
  },
  "account_name": "eospalliumss",
  "public_key": "EOS62ThFzb79uGUSedeE2rCLucFAKBoEEmfNyhfd7Y8Qcr9EvCYny",
  "org": {
    "name": "EOS Palliums",
    "website": "http://eospalliums.org",
    "email": "eospalliums@gmail.com",
    "branding":{
      "logo": "logo-eospalliums.png",
      "cover": "cover-eospalliums.png"
    },
    "location": "Beijing, China",
    "social_network": {
      "steemit": "https://steemit.com/@eospalliums",
      "twitter": "https://twitter.com/EOSPalliums",
      "facebook": "https://fb.me/EOSPalliums",
      "telegram": "https://t.me/EOSPalliums"
    }
  },
  "nodes": [
    {
      "location": {
        "id": "86",
        "name": "China"
      },
      "is_producer": false,
      "p2p_endpoint": "peer1.eospalliums.org:9876",
      "api_endpoint": "peer1.eospalliums.org:8888",
      "ssl_endpoint": ""
    }
  ]
}

=== consenlabs/eos-bp-profile/bp/eoscostarica.json
{
  "title": "EOS Costa Rica",
  "tagline": {
    "en": "Independent and Self-funded Block producer based out of Costa Rica.",
    "zh": ""
  },
  "introduce": {
    "en": "Providing the EOS network with Bare Metal Infrastructure, from a geo-strategic and politically stable location.",
    "zh": ""
  },
  "account_name": "costaricaeos",
  "public_key": "EOS7phU8qE6nPCfpkCQ2T3HmRwGg6z4v61RTLvPBBVmPWmPisZoWY",
  "org": {
    "name": "EOS Costa Rica",
    "website": "https://eoscostarica.io",
    "email": "bp@eosio.cr",
    "branding":{
      "logo": "logo-eoscostarica.png",
      "cover": "cover-eoscostarica.png"
    },
    "location": "Costa Rica",
    "social_network": {
      "steemit": "https://steemit.com/@eos-costarica",
      "twitter": "https://twitter.com/EOSCostaRica",
      "facebook": "",
      "github": "https://github.com/eoscostarica",
      "telegram": "https://t.me/eoscr"
    }
  },
  "nodes":[
    {
      "location":{
        "id":"506",
        "name":"Costa Rica"
      },
      "is_producer": false,
      "p2p_endpoint":"p2p.eosio.cr:1976",
      "api_endpoint":"",
      "ssl_endpoint":"https://api.eosio.cr"
    },
    {
      "location":{
        "id":"506",
        "country":"Costa Rica"
      },
      "is_producer": false,
      "p2p_endpoint":"p2p.eosio.cr:5418",
      "api_endpoint":"",
      "ssl_endpoint":""
    },
    {
      "location":{
        "id":"506",
        "country":"Costa Rica"
      },
      "node_type":"producer",
      "is_producer": true,
      "p2p_endpoint":"",
      "api_endpoint":"",
      "ssl_endpoint":""
    }
  ]
}

=== consenlabs/eos-bp-profile/bp/eosDublin.json
{
  "title": "EOS Dublin",
  "tagline": {
    "en": "The Irish Block Producer",
    "zh": "来自爱尔兰🇮🇪的区块链生产者"
  },
  "introduce": {
    "en": "EOS Dublin are the main hub for EOS.IO in Ireland. We believe that EOS.IO represents a global paradigm shift towards a better digital world. EOS.IO is more than a technological advance, it’s about what becomes possible when we merge technology, community and individual commitment.",
    "zh": "EOS 都柏林是EOSIO在Ireland的最主要的中心，我们相信EOS.IO代表这个全球的范例逐步向更好的数字世界的转移。EOS.IO 代表更先进的生产力，用科技给社群和个体赋能"
  },
  "account_name": "eosdublinwow",
  "public_key": "EOS5bjub7pm8H9WLMYW5ETSwfFKrEJpVWwiwK5knvGAqLVUjEpLxx",
  "org": {
    "name": "EOS Dublin",
    "website": "https://eosdublin.com",
    "email": "hello@eosdublin.com",
    "branding":{
      "logo": "logo-eosdublin.png",
      "cover": "cover-eosdublin.png"
    },
    "location": "Dublin, Ireland",
    "social_network": {
      "steemit": "https://steemit.com/@eosdublin",
      "twitter": "https://twitter.com/eosdubllin",
      "facebook": "https://www.facebook.com/eosdublin",
      "github": "https://github.com/eosdublin",
      "telegram": "https://t.me/eosdublin"
    }
  },
  "nodes": [
    {
      "location": {
        "id": "353",
        "name": "Ireland"
      },
      "is_producer": true,
      "p2p_endpoint": "",
      "api_endpoint": "",
      "ssl_endpoint": ""
    },
    {
      "location": {
        "id": "353",
        "name": "Ireland"
      },
      "is_producer": true,
      "p2p_endpoint": "",
      "api_endpoint": "",
      "ssl_endpoint": ""
    },
    {
      "location": {
        "id": "353",
        "name": "Ireland"
      },
      "is_producer": false,
      "p2p_endpoint": "p2p.one.eosdublin.io:9876",
      "api_endpoint": "http://api1.eosdublin.io",
      "ssl_endpoint": "https://api1.eosdublin.io"
    },
    {
      "location": {
        "id": "353",
        "name": "Ireland"
      },
      "is_producer": false,
      "p2p_endpoint": "p2p.two.eosdublin.io:9876",
      "api_endpoint": "http://api2.eosdublin.io",
      "ssl_endpoint": "https://api2.eosdublin.io"
    }
  ]
}
